### ISSUE TITLE
Support for one-by-one file and line replace

### ISSUE THREAD

**Issue by Dunqing** [yassinebridi/serpl#24]
Thanks for your useful tool! It would be nice to support this feature.

**Comment by yassinebridi** [comment]
Thanks.
Can you explain more why you need this.
There is already the ability to remove files you don't need for replace.
Also, i'm working on another feature to better select files, select all, bulk removing files from the list, etc...

**Comment by Dunqing** [comment]
Personally, when I have a lot of files to replace and a lot of similar files that don't need to be replaced I find it more careful to me to replace them one file at a time. Also, I know `VSCode` has the same feature.

> Also, i'm working on another feature to better select files, select all, bulk removing files from the list, etc...

That's great. That's useful too!

**Comment by yassinebridi** [comment]
Interesting, i will add this to the list, thanks for the suggestions 🙏

**Comment by julienvincent** [comment]
I have the same request. I love the tool but it's super unintuitive to me to first remove files and then perform a replace. I'd much rather replace results one-by-one.

Would love to see this feature added!

When I first used the tool I got a bit of a surprise when pressing ctrl-o as I was expecting it to operate on the item I had selected instead of the entire list.

I think the existing ctrl-o keybinding should maybe be renamed to something like "Replace all" or "Process replace on all items" to make it clearer what it does.

**Comment by yassinebridi** [comment]
Thanks for your input @julienvincent, i will prioritize this since a lot of people requested it.

**Comment by yassinebridi** [comment]
I pushed a new version adding this feature

**Comment by julienvincent** [comment]
Already trying it out! Haha it works beautifully thank you!
